version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4200:4200'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '5000:80'

  ml_service:
    build:
      context: ./ml_service
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
